version: "3"
services:
  db:
    image: mysql
    container_name: 
    ports: 
        - "3306:3306"
    environment:
        MYSQL_DATABASE: myDb
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - persistent:/var/lib/mysql
    networks:
        - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db
    ports:
        - 8001:80
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test

  www:
    build: .
    ports: 
        - "8000:80"
    volumes:
        - ./www:/var/www/html/
    links:
        - db
    networks:
        - default
volumes:
    persistent:
