name: demo

on:
  push:
    branches:
      - master
    # tags:
    #   - 'V*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Login to GitHub Packages
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username chaana-00 --password-stdin
          docker image build . -t ghcr.io/chaana-00/demo:latest
          docker push ghcr.io/chaana-00/demo:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Login to EC2
      run: |
        echo "${{secrets.GITHUB_TOKEN}}" | add-ssh -
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "\
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username chaana-00 --password-stdin \
        && docker pull ghcr.io/chaana-00/demo:latest \
        && docker ps -aq | xargs docker stop | xargs docker rm \
        && docker run -d -p 80:80 ghcr.io/chaana-00/demo:latest \
        && docker logout"
